#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
source /usr/bin/mivariable
siroot
source /usr/bin/kzombie
sync; echo 3  > /proc/sys/vm/drop_caches
swapoff -a
swapon -a
source /etc/init.d/mizram start
exit 0
