#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
contar=0
function clean_1() {
	rm -f /run/$(basename $0).pid
}

trap "clean_1; exit" 0 1 2 3 15

if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi

echo $BASHPID > /run/"$(basename $0)".pid
for i in $(ps -A -ostat,ppid | grep -e '[zZ]' | awk '{print $2}'); do
	echo "Enviando señal SIGCHLD al proceso con el PID $i"
	kill -s SIGCHLD $i
	echo "Enviando señal SIGHUP al proceso con el PID $j"
	kill -s SIGHUP $j
	let contar=$(($contar+1))
done
echo "Se han encontrado $contar procesos zombie"
