#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
source /usr/bin/mivariable
siroot
clear
echo -e "\e[00;1;92mEstado de AppArmor (yes)\e[00m"
aa-enabled
echo ""
echo -e "\e[00;1;92mEstado de Execute Disable (active)\e[00m"
dmesg | grep "Execute Disable"
echo ""
echo -e "\e[00;1;92mEstado de la swap\e[00m"
swapon -s
echo ""
echo -e "\e[00;1;92mEstado de puntos de montaje tmpfs\e[00m"
mount | grep "tmpfs"
echo ""
echo -e "\e[00;1;92mEstado del punto de montaje cgroup\e[00m"
mount | grep "/sys/fs/cgroup/systemd"
echo -e "\e[00;1;92mCgroup release agent\e[00m"
cat /dev/cgroup/cpu/release_agent
echo -e "\e[00;1;92mEstado de cgroup notify on release (1)\e[00m"
cat /sys/fs/cgroup/cpu/notify_on_release
echo ""
echo -e "\e[00;1;92mEstado de KSM (1)\e[00m"
cat /sys/kernel/mm/ksm/run
echo ""
echo -e "\e[00;1;92mEstado de transparent_hugepage\e[00m"
cat /sys/kernel/mm/transparent_hugepage/enabled
echo ""
echo -e "\e[00;1;92mEstado de DIR_MODE en adduser (0750)\e[00m"
cat /etc/adduser.conf | grep "DIR_MODE="
echo ""
echo -e "\e[00;1;92mEstado de prelink\e[00m"
cat /etc/default/prelink | grep "PRELINKING="
cat /etc/default/prelink | grep "PRELINK_OPTS="
echo ""
echo -e "\e[00;1;92mConfiguracion de limits\e[00m"
cat /etc/security/limits.conf
echo ""
echo -e "\e[00;1;92mEstado de la shell Fish\e[00m"
cat /etc/passwd | grep "fish"
echo ""
echo -e "\e[00;1;92mValores de sysctl\e[00m"
for k in $(cat /etc/sysctl.d/10-calc-mem.conf | awk '{print $1}'); do
	echo original: $(cat /etc/sysctl.d/10-calc-mem.conf | grep "$k")
	echo detectado: $(sysctl --all | grep "$k =")
	echo ""
done
for j in $(cat /etc/sysctl.d/30-misecurity.conf | awk '{print $1}'); do
	echo original: $(cat /etc/sysctl.d/30-misecurity.conf | grep "$j")
	echo detectado: $(sysctl --all | grep "$j =")
	echo ""
done
for i in $(cat /etc/sysctl.d/30-mio.conf | awk '{print $1}'); do
	echo original: $(cat /etc/sysctl.d/30-mio.conf | grep "$i")
	echo detectado: $(sysctl --all | grep "$i =")
	echo ""
done
echo original: $(cat /etc/sysctl.d/60-disableipv6.conf | grep "net.ipv6.conf.all.disable_ipv6")
echo detectado: $(sysctl --all | grep "net.ipv6.conf.all.disable_ipv6")
echo ""
echo -e "\e[00;1;92mEstado de sysfsutils (ON)\e[00m"
systemctl status sysfsutils
echo ""
echo -e "\e[00;1;92mEstado de haveged (ON)\e[00m"
systemctl status haveged
echo ""
echo -e "\e[00;1;92mEstado de Log2RAM (ON)\e[00m"
systemctl status log2ram
echo ""
echo -e "\e[00;1;92mEstado de SSH (ON)\e[00m"
systemctl status ssh
echo ""
echo -e "\e[00;1;92mEstado de SSHGuard (ON)\e[00m"
systemctl status sshguard
echo ""
echo -e "\e[00;1;92mEstado del Governador del CPU\e[00m"
cpupower frequency-info
echo ""
echo -e "\e[00;1;92mEstado de upower\e[00m"
systemctl status upower
echo ""
echo -e "\e[00;1;92mEstado de ksmtuned\e[00m"
if [[ $(dpkg --get-selections | grep -w "ksmtuned" | awk '{print $1}' | head -1) = ksmtuned ]]; then
	systemctl status ksmtuned
fi
echo ""
echo -e "\e[00;1;92mJaulas de Firejail activas\e[00m"
firejail --list
echo ""
echo -e "\e[00;1;92mDispositivos USB autorizados\e[00m"
usbguard list-devices
echo ""
echo -e "\e[00;1;92mFinalizado.\e[00m"
exit 0
