#! /bin/sh
### BEGIN INIT INFO
# Provides:          mizram
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Should-Start:
# Should-Stop:
# X-Start-Before:
# X-Stop-After:
# Default-Start:     S
# Default-Stop:      0 1 6
# Short-Description: Cgroup release agent
# Description:       Cgroup release agent
### END INIT INFO

case "$1" in
  start)
	mkdir -p /dev/cgroup/cpu
	mount -t cgroup cgroup /dev/cgroup/cpu -o cpu
	mkdir -m 0777 /dev/cgroup/cpu/user
	echo "/usr/bin/cgroup_clean" > /dev/cgroup/cpu/release_agent
	echo "1" > /sys/kernel/mm/ksm/run
	;;
  stop)
	;;
  status)
  	echo "Cgroup release agent"
  	cat /dev/cgroup/cpu/release_agent
  	echo "Estado de KSM"
  	cat /sys/kernel/mm/ksm/run
  	;;
  *)
	echo "Usage: $SCRIPTNAME {start|stop|status}"
	exit 1
	;;
esac
