#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
trap "rm -f /run/$(basename $0).pid; exit" 0 1 2 3 15
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi
echo "$BASHPID" > /run/$(basename $0).pid
mylog="/var/log/$(basename $0).log"
echo "" > $mylog
exec 2>>$mylog
prelink -amfR --exec-shield
exit 0
