#!/usr/bin/env bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
#set -euo pipefail
LC_ALL=C
SECONDS=0
mylog="/var/log/$(basename $0).log"
LOCKFILE="/tmp/$(basename $0)_$(whoami)"
LOCKFD="150"
quien=$(who | cut -d' ' -f1 | sort | uniq)
ss=/home/$quien/.ssh
gg=/home/$quien/.gnupg
gdonde=$gg/gpg.conf
name="/etc/sysctl.d/10-calc-mem.conf"
limi="/etc/security/limits.conf"
bah="/root/.bashrc"
etbah="/etc/bash.bashrc"
mise="/etc/sysctl.d/30-misecurity.conf"
fst="/etc/fstab"
emod="/etc/modules"
logd="/etc/login.defs"
rkh="/etc/rkhunter.conf"
yo="/home/$quien/.bashrc"
sysf="/etc/sysfs.conf"
log2="/etc/log2ram.conf"
cpas="/etc/pam.d/common-password"

function calcmem() {
	memor=$(grep MemTotal /proc/meminfo | awk '{print $2}')
	mb=$(( $memor * 1024 ))
	mf=$(( $memor * 3/100 ))
	fm=$(( $mb / 4194304 * 256 ))
	mo=$(( $mb * 0,10 / 65536 ))
	mt=$(( $fm * 2 ))
	page_size=$(getconf PAGE_SIZE)
	phys_pages=$(getconf _PHYS_PAGES)
	shmall=$(( $phys_pages / 2 ))
	shmmax=$(( $shmall * $page_size ))
	echo "kernel.shmmax = $shmmax" > "$name"
	echo "kernel.shmall = $shmall" >> "$name"
	echo "vm.min_free_kbytes = $mf" >> "$name"
	echo "fs.file-max = $fm" >> "$name"
	#echo "net.ipv4.tcp_max_orphans = $mo" >> "$name"
	echo "net.ipv4.tcp_max_tw_buckets = $mt" >> "$name"
	if (( $memor < 1024000 )); then
	        echo "vm.dirty_ratio = 30" >> "$name"
	        echo "vm.dirty_background_ratio = 3" >> "$name"
	        echo "vm.dirty_expire_centisecs = 750" >> "$name"
	        echo "vm.dirty_writeback_centisecs = 125" >> "$name"
	else
	        if (( $memor > 4096000 )); then
	            echo "vm.swappiness = 10" >> "$name"
	            echo "vm.vfs_cache_pressure = 50" >> "$name"
	        fi
	        if (( $memor < 8192000 )); then
	            echo "vm.dirty_ratio = 25" >> "$name"
	            echo "vm.dirty_background_ratio = 4" >> "$name"
	            echo "vm.dirty_expire_centisecs = 1500" >> "$name"
	            echo "vm.dirty_writeback_centisecs = 250" >> "$name"
	        else
	            echo "vm.dirty_ratio = 20" >> "$name"
	            echo "vm.dirty_background_ratio = 5" >> "$name"
	            echo "vm.dirty_expire_centisecs = 3000" >> "$name"
	            echo "vm.dirty_writeback_centisecs = 500" >> "$name"
	        fi
	fi
	sysctl --system > /dev/null
}

function clean_1() {
	rm -f /run/$(basename $0).pid
	rm -rf /tmp/*
	rm -rf /var/tmp/*
	rm -f $LOCKFILE
}

function lock() {
	echo {LOCKFD}>$LOCKFILE
	flock -n $LOCKFD
}

function exit_error() {
	echo -e "\e[00;31mYa hay una instancia en ejecución. Saliendo\e[00m"
	exit 1
}

trap "clean_1; exit" 0 1 2 3 9 15
if [[ "$EUID" != "0" ]]; then
	echo -e "\e[00;31mERROR: Debes ser root.\e[00m"
	exit 1
fi
echo $BASHPID > /run/"$(basename $0)".pid
echo "" > $mylog
exec 2>>$mylog

lock || exit_error

echo $quien
if [[ -z $(grep -i 'tmpfs /tmp tmpfs rw,nodev,noatime,nosuid,noexec 0 0' $fst) ]]; then
	echo "tmpfs /tmp tmpfs rw,nodev,noatime,nosuid,noexec 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /var/cache/samba tmpfs rw,noatime,nodev 0 0' $fst) ]]; then
	echo "tmpfs /var/cache/samba tmpfs rw,noatime,nodev 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /var/cache/apt/archives tmpfs rw,noatime,nodev 0 0' $fst) ]]; then
	echo "tmpfs /var/cache/apt/archives tmpfs rw,noatime,nodev 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /var/cache/apt/apt-fast tmpfs rw,noatime,nodev 0 0' $fst) ]]; then
	echo "tmpfs /var/cache/apt/apt-fast tmpfs rw,noatime,nodev 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /var/tmp tmpfs rw,noexec,nodev,noatime,nosuid 0 0' $fst) ]]; then
	echo "tmpfs /var/tmp tmpfs rw,noexec,nodev,noatime,nosuid 0 0" >> $fst
fi
if [[ -z $(grep -i 'proc /proc proc defaults,hidepid=2 0 0' $fst) ]]; then
	echo "proc /proc proc defaults,hidepid=2 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /run tmpfs rw,nosuid,noexec,nodev,noatime,mode=755 0 0' $fst) ]]; then
	echo "tmpfs /run tmpfs rw,nosuid,noexec,nodev,noatime,mode=755 0 0" >> $fst
fi
if [[ -z $(grep -i 'tmpfs /dev/shm tmpfs defaults,nodev,nosuid,noexec 0 0' $fst) ]]; then
	echo "tmpfs /dev/shm tmpfs defaults,nodev,nosuid,noexec 0 0" >> $fst
fi
if [[ -f /etc/initramfs-tools/initramfs.conf ]]; then
	sed -i 's/MODULES=most/MODULES=dep/g' /etc/initramfs-tools/initramfs.conf
	update-initramfs -c -k all
fi
if ! [[ -f /root/.base ]]; then
	#echo "tmpfs /var/spool tmpfs rw,noatime,nodev 0 0" >> $fst
	sed -i "s/127.0.0.1\tlocalhost/127.0.0.1\tlocalhost $HOSTNAME/g" /etc/hosts
	sed -i 's/GRUB_TIMEOUT_STYLE=hidden/GRUB_TIMEOUT_STYLE=menu/g' /etc/default/grub
	sed -i 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=3/g' /etc/default/grub
	update-grub2
	touch /root/.base
fi
if ! [[ -f /home/$quien/.gnupg/gpg.conf.old ]]; then
	mkdir -p $gg
	mv -f $gdonde $gg/gpg.conf.old
	cp -f /usr/share/gpg.conf.sample $gdonde
	chown -R $quien:$quien $gg
	chmod -R 700 $gg
fi
if ! [[ -f /usr/bin/mizram ]]; then
	ln -s /etc/init.d/mizram /usr/bin/mizram
fi
if [[ -z $(grep -i lp $emod) ]]; then
	echo "lp" >> $emod
fi
if [[ -z $(grep -i freevxfs $emod) ]]; then
	echo "freevxfs" >> $emod
fi
if [[ -z $(grep -i jffs2 $emod) ]]; then
	echo "jffs2" >> $emod
fi
if [[ -z $(grep -i udf $emod) ]]; then
	echo "udf" >> $emod
fi
if [[ -z $(grep -i cramfs $emod) ]]; then
	echo "cramfs" >> $emod
fi
if [[ -z $(grep -i hfs $emod) ]]; then
	echo "hfs" >> $emod
fi
if [[ -z $(grep -i hfsplus $emod) ]]; then
	echo "hfsplus" >> $emod
fi
if [[ -z $(grep -i "alias rotorar='unrar e -kb -y'" $etbah) ]]; then
	echo "alias rotorar='unrar e -kb -y'" >> $etbah
fi
if [[ -z $(grep -i 'export HISTIGNORE="ls:clear"' $etbah) ]]; then
	echo 'export HISTIGNORE="ls:clear"' >> $etbah
fi
if [[ -z $(grep -i "shopt -s checkwinsize" $etbah) ]]; then
	echo "shopt -s checkwinsize" >> $etbah
fi
if [[ -z $(grep -i "HISTFILESIZE=2000" $etbah) ]]; then
	echo "HISTFILESIZE=2000" >> $etbah
fi
if [[ -z $(grep -i "HISTSIZE=1000" $etbah) ]]; then
	echo "HISTSIZE=1000" >> $etbah
fi
if [[ -z $(grep -i "HISTCONTROL=ignoreboth" $etbah) ]]; then
	echo "HISTCONTROL=ignoreboth" >> $etbah
fi
if [[ -z $(lscpu | grep GenuineIntel) ]]; then	
	if [[ -z $(grep -i 'INTEL_BATCH="1"' /etc/environment) ]]; then
		echo 'INTEL_BATCH="1"' >> /etc/environment
	fi
fi
if [[ -z $(grep -i "#kernel.kptr_restrict = 1" /etc/sysctl.d/10-kernel-hardening.conf) ]]; then
	sed -i 's/kernel.kptr_restrict = 1/#kernel.kptr_restrict = 1/g' /etc/sysctl.d/10-kernel-hardening.conf
fi
if [[ -z $(grep -i "#kernel.sysrq = 176" /etc/sysctl.d/10-magic-sysrq.conf) ]]; then
	sed -i 's/kernel.sysrq = 176/#kernel.sysrq = 176/g' /etc/sysctl.d/10-magic-sysrq.conf
fi	
if [[ -z $(grep -i "#net.ipv4.conf.default.rp_filter=2" /etc/sysctl.d/10-network-security.conf) ]]; then
	sed -i 's/net.ipv4.conf.default.rp_filter=2/#net.ipv4.conf.default.rp_filter=2/g' /etc/sysctl.d/10-network-security.conf
fi		
if [[ -z $(grep -i "#net.ipv4.conf.all.rp_filter=2" /etc/sysctl.d/10-network-security.conf) ]]; then
	sed -i 's/net.ipv4.conf.all.rp_filter=2/#net.ipv4.conf.all.rp_filter=2/g' /etc/sysctl.d/10-network-security.conf
fi	
if [[ -z $(grep -i "#kernel.yama.ptrace_scope = 1" /etc/sysctl.d/10-ptrace.conf) ]]; then
	sed -i 's/kernel.yama.ptrace_scope = 1/#kernel.yama.ptrace_scope = 1/g' /etc/sysctl.d/10-ptrace.conf
fi
if [[ -z $(grep -i 'WARNING: unauthorized access to this system is prohibited.' /etc/issue) ]]; then
	echo 'WARNING: unauthorized access to this system is prohibited.' >> /etc/issue
fi
if [[ -z $(grep -i 'WARNING: unauthorized access to this system is prohibited.' /etc/issue.net) ]]; then
	echo 'WARNING: unauthorized access to this system is prohibited.' >> /etc/issue.net
fi
if [[ -z $(grep -i '#Listen localhost:631' /etc/cups/cupsd.conf) ]]; then
	sed -i 's/Listen localhost:631/#Listen localhost:631/g' /etc/cups/cupsd.conf
	chmod 600 /etc/cups/cupsd.conf
fi
if [[ -f /etc/init.d/rc ]]; then
	sed -i 's/umask 022/umask 027/g' /etc/init.d/rc
fi
if [[ -f /etc/cups/cups-browsed.conf ]]; then
	sed -i 's/BrowseRemoteProtocols dnssd cups/BrowseRemoteProtocols none/g' /etc/cups/cups-browsed.conf
	sed -i 's/# BrowseProtocols none/BrowseProtocols none/g' /etc/cups/cups-browsed.conf
fi
if [[ -f /etc/avahi/avahi-daemon.conf ]]; then
	sed -i 's/#host-name=foo/enable-dbus=no/g' /etc/avahi/avahi-daemon.conf
fi
if [[ -f $logd ]]; then
	sed -i 's/# SHA_CRYPT_MIN_ROUNDS 5000/SHA_CRYPT_MIN_ROUNDS 5000/g' $logd
	sed -i 's/# SHA_CRYPT_MAX_ROUNDS 5000/SHA_CRYPT_MAX_ROUNDS 10000/g' $logd
	sed -i 's/PASS_MAX_DAYS\t99999/PASS_MAX_DAYS\t180/g' $logd
	sed -i 's/PASS_MIN_DAYS\t0/PASS_MIN_DAYS\t1/g' $logd
	sed -i 's/UMASK\t\t022/UMASK\t\t027/g' $logd
	if [[ -z $(grep -i 'HOME_MODE 0750' $logd) ]]; then
		echo "HOME_MODE 0750" >> $logd
	fi
fi
if [[ -f /etc/adduser.conf ]]; then
	sed -i 's_DSHELL=/bin/bash_DSHELL=/usr/bin/fish_g' /etc/adduser.conf
	sed -i 's/DIR_MODE=0755/DIR_MODE=0750/g' /etc/adduser.conf
fi
if [[ -f /etc/default/keyboard ]]; then
	sed -i 's/XKBOPTIONS=""/XKBOPTIONS="terminate:ctrl_alt_bksp"/g' /etc/default/keyboard
fi
if [[ -f /etc/passwd ]]; then
	sed -i 's_/bin/bash_/usr/bin/fish_g' /etc/passwd
fi
if [[ -f /etc/default/prelink ]]; then
	sed -i 's/PRELINKING=unknown/PRELINKING=yes/g' /etc/default/prelink
	sed -i 's/PRELINK_OPTS=-mR/PRELINK_OPTS=-amR/g' /etc/default/prelink
fi
if [[ -f $rkh ]]; then
	sed -i 's\UPDATE_MIRRORS=0\UPDATE_MIRRORS=1\g' $rkh
	sed -i 's\MIRRORS_MODE=1\MIRRORS_MODE=0\g' $rkh
	sed -i 's\WEB_CMD="/bin/false"\#WEB_CMD="/bin/false"\g' $rkh
	sed -i 's\SCRIPTWHITELIST=/usr/bin/egrep\SCRIPTWHITELIST=/bin/egrep\g' $rkh
	sed -i 's\SCRIPTWHITELIST=/usr/bin/fgrep\SCRIPTWHITELIST=/bin/fgrep\g' $rkh
fi
if [[ -f /etc/default/motd-news ]]; then
	sed -i 's\ENABLED=1\ENABLED=0\g' /etc/default/motd-news
fi
if [[ -f /etc/systemd/system.conf ]]; then
	sed -i 's\#DefaultTimeoutStopSec=90s\DefaultTimeoutStopSec=10s\g' /etc/systemd/system.conf
	sed -i 's\#CtrlAltDelBurstAction=reboot-force\CtrlAltDelBurstAction=reboot-force\g' /etc/systemd/system.conf
fi
if [[ -f /etc/xdg/autostart/tracker-miner-fs.desktop ]]; then
	mv -f /etc/xdg/autostart/tracker-miner-fs.desktop /root/
	mv -f /etc/xdg/autostart/tracker-extract.desktop /root/
	mv -f /etc/xdg/autostart/tracker-miner-apps.desktop /root/
	mv -f /etc/xdg/autostart/tracker-miner-user-guides.desktop /root/
	mv -f /etc/xdg/autostart/tracker-store.desktop /root/
	chmod 666 /usr/libexec/tracker-miner-fs
	#chmod 666 /usr/libexec/tracker-store
	chmod 666 /usr/libexec/tracker-extract
	chmod 666 /usr/libexec/tracker-writeback
	echo "TimeoutStartSec=2" >> /usr/share/dbus-1/services/org.freedesktop.Tracker1.service
fi
if [[ $(dpkg --get-selections | grep -w "ssh" | awk '{print $1}' | head -1) = ssh ]]; then
	mkdir -p $ss
	chown -R $quien:$quien $ss
	chmod -R 700 $ss
	if ! [[ -f /etc/ssh/moduli.old ]]; then
		awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp
		mv -f /etc/ssh/moduli /etc/ssh/moduli.old
		mv -f /etc/ssh/moduli.tmp /etc/ssh/moduli
	fi
fi
if ! [[ -d /home/$quien/.config/autostart ]]; then
	mkdir -p /home/$quien/.config/autostart
fi
if ! [[ -d /etc/sysctl.d ]]; then
	mkdir -p /etc/sysctl.d
fi
if [[ -z $(grep -i '"$PS1"' $yo) ]]; then
	echo 'if [ "$PS1" ] ;' >> $yo
	echo '	then mkdir -m 0700 /dev/cgroup/cpu/user/$$' >> $yo
	echo '	echo $$ > /dev/cgroup/cpu/user/$$/tasks' >> $yo
	echo '	echo "1" > /dev/cgroup/cpu/user/$$/notify_on_release' >> $yo
	echo 'fi' >> $yo
fi
if [[ -z $(grep -i '"$PS1"' $bah) ]]; then
	echo 'if [ "$PS1" ] ;' >> $bah
	echo '	then mkdir -m 0700 /dev/cgroup/cpu/user/$$' >> $bah
	echo '	echo $$ > /dev/cgroup/cpu/user/$$/tasks' >> $bah
	echo '	echo "1" > /dev/cgroup/cpu/user/$$/notify_on_release' >> $bah
	echo 'fi' >> $bah
fi
yes "" | sensors-detect
echo "fs.suid_dumpable = 0" > $mise
echo "fs.aio-max-nr = 1048576" >> $mise
echo "fs.protected_hardlinks = 1" >> $mise
echo "fs.protected_symlinks = 1" >> $mise
echo "vm.mmap_min_addr = 65536" >> $mise
echo "vm.oom_kill_allocating_task = 1" >> $mise
echo "vm.watermark_scale_factor = 200" >> $mise
echo "vm.overcommit_memory = 1" >> $mise
echo "kernel.core_uses_pid = 1" >> $mise
echo "kernel.dmesg_restrict = 1" >> $mise
echo "kernel.kptr_restrict = 2" >> $mise
echo "kernel.msgmnb = 65535" >> $mise
echo "kernel.msgmax = 65535" >> $mise
echo "kernel.pid_max = 65535" >> $mise
echo "kernel.randomize_va_space = 2" >> $mise
echo "kernel.sched_autogroup_enabled = 1" >> $mise
echo "kernel.sched_rt_runtime_us = 950000" >> $mise
echo "kernel.sched_migration_cost_ns = 5000000" >> $mise
echo "kernel.shmmni = 8192" >> $mise
echo "kernel.sysrq = 0" >> $mise
echo "kernel.yama.ptrace_scope = 2" >> $mise
echo "kernel.unprivileged_bpf_disabled = 1" >> $mise
echo "kernel.kexec_load_disabled = 1" >> $mise
echo "password requisite pam_cracklib.so retry=3 minlen=16 difok=3 ucredit=-1 lcredit=-2 dcredit=-2 ocredit=-2" > $cpas
echo "password [success=1 default=ignore] pam_unix.so obscure use_authtok try_first_pass sha512 rounds=65536" >> $cpas
echo "password requisite pam_deny.so" >> $cpas
echo "password required pam_permit.so" >> $cpas
echo "password optional pam_gnome_keyring.so" >> $cpas
echo "# /etc/security/limits.conf" > $limi
echo "* hard core 0" >> $limi
echo "* hard nproc 1000" >> $limi
echo "* soft nofile 2000" >> $limi
echo "* hard nofile 2000" >> $limi
echo "# End of file" >> $limi
echo "net.ipv6.conf.all.disable_ipv6 = 1" > /etc/sysctl.d/60-disableipv6.conf
echo "net.ipv6.conf.default.disable_ipv6 = 1" >> /etc/sysctl.d/60-disableipv6.conf
echo "net.ipv6.conf.lo.disable_ipv6 = 1" >> /etc/sysctl.d/60-disableipv6.conf
echo "kernel/mm/transparent_hugepage/enabled" = always > $sysf
echo "kernel/mm/transparent_hugepage/khugepaged/pages_to_scan = 20000" >> $sysf
echo "kernel/mm/ksm/run = 1" >> $sysf
echo "kernel/mm/ksm/pages_to_scan = 20000" >> $sysf
echo "kernel/mm/ksm/sleep_millisecs = 200" >> $sysf
echo "kernel/security/lockdown = confidentiality" >> $sysf
echo "fs/cgroup/cpu/notify_on_release = 1" >> $sysf
echo "fs/cgroup/cpu/release_agent = /usr/bin/cgroup_clean" >> $sysf
#echo "devices/system/cpu/intel_pstate/no_turbo = 1" >> $sysf
echo "[Journal]" > /etc/systemd/journald.conf
echo "SystemMaxUse=50M" >> /etc/systemd/journald.conf
echo "multi on" > /etc/host.conf
echo "order hosts,bind" >> /etc/host.conf
echo "SIZE=128M" > $log2
echo "USE_RSYNC=true" >> $log2
echo "MAIL=false" >> $log2
echo 'PATH_DISK="/var/log"' >> $log2
echo "ZL2R=false" >> $log2
echo "COMP_ALG=lz4" >> $log2
echo "LOG_DISK_SIZE=100M" >> $log2
sed -i 's/rotate 4/rotate 1/g' /etc/logrotate.conf
sed -i 's/weekly/daily/g' /etc/logrotate.conf
sed -i 's/rotate 7/rotate 1/g' /etc/logrotate.d/rsyslog
sed -i 's/rotate 4/rotate 1/g' /etc/logrotate.d/rsyslog
sed -i 's/weekly/daily/g' /etc/logrotate.d/rsyslog
sed -i 's/#SystemMaxFiles=100/SystemMaxFiles=7/g' /etc/systemd/journald.conf
chmod 444 /usr/libexec/evolution-calendar-factory
chmod 750 /home/*
calcmem
ssh-keygen -A
echo "AppArmor status:"
aa-enabled
echo "Configurando Firejail"
firecfg
firecfg --fix
for i in $(ls -l /home | awk '{print $9}' | grep -v "lost+found" | tail -n +2); do
	firecfg --add-users $i
done
apparmor_parser -r /etc/apparmor.d/firejail-default
aa-enforce firejail-default
echo "apparmor" > /etc/firejail/globals.local
if [[ -z $(grep -i "apparmor" /etc/firejail/globaltime.profile) ]]; then
	echo "apparmor" >> /etc/firejail/globaltime.profile
fi
if [[ -z $(grep -i "apparmor" /etc/firejail/default.profile) ]]; then
	echo "apparmor" >> /etc/firejail/default.profile
fi
echo "Finalizado $(date +%d/%m/%Y)" >> $mylog
echo "Duracion $SECONDS segundos" >> $mylog
echo "Duracion $SECONDS segundos"
echo "" >> $mylog
echo -e "\e[00;1;92mFinalizado. Se recomienda reiniciar el equipo.\e[00m"
exit 0
