#!/bin/bash
# Made by Sinfallas <sinfallas@yahoo.com>
# Licence: GPL-2
LC_ALL=C
source /usr/bin/mivariable
siroot
echo "3" > /proc/sys/kernel/printk
echo "3" > /proc/sys/vm/drop_caches
echo "256" > /proc/sys/vm/min_free_kbytes
echo "1" > /proc/sys/vm/overcommit_memory
echo "1" > /proc/sys/vm/oom_kill_allocating_task
echo "0" > /proc/sys/vm/oom_dump_tasks
/usr/bin/sdmem -ll
