#!/bin/bash

case "$1" in
	configure)
		chmod +x /etc/init.d/mizram
		chmod +x /etc/profile.d/miulimit.sh
		chmod +x /usr/bin/kzombie
		chmod +x /usr/bin/passgen-all
		chmod +x /usr/bin/post-apt
		chmod +x /usr/bin/clearmem
		chmod +x /usr/bin/sinfallas-base
		update-rc.d mizram defaults
		systemctl daemon-reload
		systemctl enable cpupower.service
		source /usr/bin/sinfallas-base
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|abort-deconfigure|abort-remove)
	;;

	*)
		echo "postinst fue invocado con argumentos desconocidos \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
exit 0
