#!/bin/bash

case "$1" in
	configure)
		chmod 777 /etc/init.d/mizram
		chmod 644 /etc/systemd/system/cpupower.service
		chmod 644 /etc/systemd/system/wiperam.service
		chmod 777 /etc/profile.d/miulimit.sh
		chmod 777 /usr/bin/kzombie
		chmod 777 /usr/bin/passgen-all
		chmod 777 /usr/bin/post-apt
		chmod 777 /usr/bin/clearmem
		chmod 777 /usr/bin/sinfallas-base
		chmod 777 /usr/bin/cgroup_clean
		chmod 777 /usr/bin/mistatus
		chmod 777 /usr/bin/mijail
		chmod 777 /usr/bin/wiperam
		chmod 777 /usr/bin/beats
		update-rc.d mizram defaults
		systemctl daemon-reload
		systemctl enable cpupower.service
		systemctl disable wiperam.service
		if ! [[ -f /root/.sinfallas/actualizar ]]; then
			source /usr/bin/sinfallas-base
			source /usr/bin/mijail
		fi
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear|abort-deconfigure|abort-remove)
	;;

	*)
		echo "postinst fue invocado con argumentos desconocidos \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
exit 0
