#!/bin/sh
set -e

case "$1" in
	remove|purge)
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm fue invocado con argumentos desconocidos \`$1'" >&2
		exit 1
	;;

esac

#DEBHELPER#
exit 0
