#!/bin/bash
set -e

case "$1" in
	remove|purge)
		echo "" > /etc/locale.nopurge
		echo "" > /etc/sysfs.conf
		if [[ -f /etc/sysctl.d/30-mio.conf ]]; then
			rm -f /etc/sysctl.d/30-mio.conf
		fi
		if [[ -f /etc/init.d/mizram ]]; then
			rm -f /etc/init.d/mizram
		fi
		if [[ -f /etc/systemd/system/cpupower.service ]]; then
			rm -f /etc/systemd/system/cpupower.service
		fi
		if [[ -f /etc/systemd/system/wiperam.service ]]; then
			rm -f /etc/systemd/system/wiperam.service
		fi
		if [[ -f /usr/bin/kzombie ]]; then
			rm -f /usr/bin/kzombie
		fi
		if [[ -f /usr/bin/passgen-all ]]; then
			rm -f /usr/bin/passgen-all
		fi
		if [[ -f /etc/apt/apt.conf.d/10mio ]]; then
			rm -f /etc/apt/apt.conf.d/10mio
		fi
		if [[ -f /usr/bin/post-apt ]]; then
			rm -f /usr/bin/post-apt
		fi
		if [[ -f /usr/bin/wiperam ]]; then
			rm -f /usr/bin/wiperam
		fi
		if [[ -f /etc/systemd/coredump.conf ]]; then
			rm -f /etc/systemd/coredump.conf
		fi
		if [[ -f /etc/profile.d/miulimit.sh ]]; then
			rm -f /etc/profile.d/miulimit.sh
		fi
		if [[ -f /etc/ssh/sshd_config ]]; then
			rm -f /etc/ssh/sshd_config
		fi
		if [[ -f /usr/bin/clearmem ]]; then
			rm -f /usr/bin/clearmem
		fi
		if [[ -f /usr/bin/mistatus ]]; then
			rm -f /usr/bin/mistatus
		fi		
		if [[ -f /root/.sinfallas/tracker-miner-fs.desktop ]]; then
			mv -f /root/.sinfallas/tracker-miner-fs.desktop /etc/xdg/autostart/
		fi
		if [[ -f /root/.sinfallas/tracker-extract.desktop ]]; then
			mv -f /root/.sinfallas/tracker-extract.desktop /etc/xdg/autostart/
		fi
		if [[ -f /root/.sinfallas/tracker-miner-apps.desktop ]]; then
			mv -f /root/.sinfallas/tracker-miner-apps.desktop /etc/xdg/autostart/
		fi
		if [[ -f /root/.sinfallas/tracker-miner-user-guides.desktop ]]; then
			mv -f /root/.sinfallas/tracker-miner-user-guides.desktop /etc/xdg/autostart/
		fi
		if [[ -f /root/.sinfallas/tracker-store.desktop ]]; then
			mv -f /root/.sinfallas/tracker-store.desktop /etc/xdg/autostart/
		fi
		if [[ -f /etc/sysctl.d/60-disableipv6.conf ]]; then
			rm -f /etc/sysctl.d/60-disableipv6.conf
		fi
		if [[ -f /root/.base ]]; then
			rm -f /root/.base
		fi
		if [[ -f /usr/bin/mizram ]]; then
			rm -f /usr/bin/mizram
		fi
		if [[ -f /usr/share/gpg.conf.sample ]]; then
			rm -f /usr/share/gpg.conf.sample
		fi
		if [[ -f /usr/bin/sinfallas-base ]]; then
			rm -f /usr/bin/sinfallas-base
		fi
		if [[ -f /etc/ssh/moduli ]]; then
			rm -f /etc/ssh/moduli
		fi
		if [[ -f /etc/ssh/moduli.old ]]; then
			mv -f /etc/ssh/moduli.old /etc/ssh/moduli
		fi
		if [[ -f /usr/bin/cgroup_clean ]]; then
			rm -f /usr/bin/cgroup_clean
		fi
		if [[ -f /usr/bin/mijail ]]; then
			rm -f /usr/bin/mijail
		fi		
		if [[ -f /etc/securetty ]]; then
			rm -f /etc/securetty
		fi
		if [[ -f /etc/thermald/thermal-conf.xml ]]; then
			rm -f /etc/thermald/thermal-conf.xml
		fi
		if [[ -f /usr/bin/beats ]]; then
			rm -f /usr/bin/beats
		fi
		echo "" > /etc/sysctl.d/30-misecurity.conf
		firecfg --clean
	;;

	upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "postrm fue invocado con argumentos desconocidos \`$1'" >&2
		exit 1
	;;

esac

#DEBHELPER#
exit 0
