#!/bin/sh
set -e

case "$1" in
	install)
	;;

	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;

	*)
		echo "preinst fue invocado con argumentos desconocidos \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
exit 0
